Branch name validation (little bit overengineered)
AGH-Code-Industry/czasoport pull request #13
Opened 2023-08-01 22:19 UTC by vLesio

2023-08-02 21:15 UTC, empieniazek requested changes

2023-08-02 21:15 UTC, empieniazek commented on .coin/InitializeCoinAdditions.cs
> +        if (DateTime.Parse(text).AddHours(12) < DateTime.Now) {
Hours value could be save in static variable to ensure easy access

2023-08-02 21:15 UTC, empieniazek commented on .coin/InitializeCoinAdditions.cs
> +        p.StartInfo = new ProcessStartInfo("python", "./.coin/coin-initializer.py");
Need a comment about what is happening here - why do we call python file?

2023-08-02 21:15 UTC, empieniazek commented on .coin/InitializeCoinAdditions.cs
> +        while(!p.HasExited){}
Is it 100% safe?

2023-08-02 21:15 UTC, empieniazek commented on .coin/coin-initializer.py
> +# In case of any questions, please contact me via Discord
Add your discord nickname

2023-08-02 21:15 UTC, empieniazek commented on .coin/coin-initializer.py
> +time.sleep(3)
Why do we need sleep here?

2023-08-02 21:15 UTC, empieniazek commented on .coin/hooks/pre-push
> +# In case of any questions, please contact me via Discord
Add you discord nickname

2023-08-02 21:15 UTC, empieniazek commented on .coin/coin-initializer.py
> +# This script runs all scripts that start with "initialize-" in the .coin folder
When and how often this script is called? I think it is worth to write it down

2023-08-02 21:15 UTC, empieniazek commented on .coin/initialize-hooks.py
> +# In case of any questions, please contact me via Discord
Add discord nickname

2023-08-02 21:15 UTC, empieniazek commented on .coin/initialize-hooks.py
> +# This script initializes all the hooks present in the .coin\hooks folder
Imho if you want your script to be easy to understand explain it further (why we need to copy hooks to .git)

2023-08-02 21:15 UTC, empieniazek commented on Assets/Scripts/InitializeCoinAdditions.cs
Why same script is in assets and in .coin?

2023-08-02 21:18 UTC, vLesio commented on .coin/InitializeCoinAdditions.cs
> +        p.StartInfo = new ProcessStartInfo("python", "./.coin/coin-initializer.py");
Because there are python scripts

2023-08-02 21:19 UTC, vLesio commented on .coin/InitializeCoinAdditions.cs
> +        while(!p.HasExited){}
No it is not, but I will work on that in the future. There will be some documentation provided on what dependencies are needed to run this

2023-08-02 21:20 UTC, vLesio commented on .coin/coin-initializer.py
> +time.sleep(3)
Normally the windows will close after finishing tasks - but for now we have no way of knowing if the tasks were successful. This will show result of the scripts for some time on the screen to help catch unexpected results

2023-08-02 21:22 UTC, vLesio commented on .coin/initialize-hooks.py
> +# This script initializes all the hooks present in the .coin\hooks folder
"why we need to copy hooks to .git" - this is not a tutorial on what the script does and script itself is not a place to explain motives behind its existence

2023-08-02 21:25 UTC, vLesio commented on Assets/Scripts/InitializeCoinAdditions.cs
.coin folder will be available as standalone package for other projects, and I wanted to include all files that are needed there so they can be copied and put in their correct places

2023-08-02 21:30 UTC, vLesio commented on .coin/InitializeCoinAdditions.cs
> +        if (DateTime.Parse(text).AddHours(12) < DateTime.Now) {
For projects administrators it will be the same amount of work to change it - modify one line of code. Note that there is `AddHours` function, so with one static variable we would be able to change only the difference in hours, not for example in minutes or days. To sum up, it is not hard for someone to change this manually to `.AddMinutes()` or `.AddDays()` or just change one int to another - information about how to do this will be available on official release.

2023-08-02 21:34 UTC, empieniazek commented on .coin/initialize-hooks.py
> +# This script initializes all the hooks present in the .coin\hooks folder
it is generally a good practice to include comments in your scripts to explain why certain sections of code exist and what they do. Comments serve as documentation for the code, helping you and other developers understand the purpose and functionality of various parts of the script. This can be particularly helpful when you or someone else revisits the code after some time has passed.

Here are some reasons why including comments is beneficial:

Code Clarity: Comments provide additional context and clarity to the code, making it easier to read and understand. They can help prevent misunderstandings or confusion about the code's intentions.

Maintainability: When you or others need to modify or extend the code in the future, comments act as a guide, helping you quickly grasp the logic behind each section.

Collaboration: When collaborating with other developers, comments enable effective communication and ensure everyone is on the same page regarding the code's purpose and functionality.

Debugging and Troubleshooting: Comments can be helpful during debugging sessions, as they provide insights into the thought process behind the code. They can help identify potential issues or points of improvement.

Learning and Teaching: For educational purposes, comments are invaluable as they can assist learners in understanding the code and learning best practices.

2023-08-02 21:35 UTC, empieniazek commented on .coin/coin-initializer.py
> +time.sleep(3)
Logfile seems to be better idea for debugging and catching unexpected results than 3s window?

2023-08-02 21:39 UTC, empieniazek commented on .coin/InitializeCoinAdditions.cs
> +        p.StartInfo = new ProcessStartInfo("python", "./.coin/coin-initializer.py");
Python files are rather rarely used in unity C# games. Standard developer will be surprised that his repo calls python scripts,

2023-08-02 21:41 UTC, vLesio commented on .coin/coin-initializer.py
> +time.sleep(3)
Hmmm

2023-08-02 21:42 UTC, vLesio commented on .coin/initialize-hooks.py
> +# This script initializes all the hooks present in the .coin\hooks folder
Good Chat GPT output - next time give something from yourself

2023-08-02 21:42 UTC, empieniazek commented on .coin/initialize-hooks.py
> +# This script initializes all the hooks present in the .coin\hooks folder
Still waiting for changes

2023-08-02 21:43 UTC, empieniazek commented on .coin/InitializeCoinAdditions.cs
> +        if (DateTime.Parse(text).AddHours(12) < DateTime.Now) {
As long as the script will not be getting bigger and bigger, which you will never know. So imo it's better to be prepare ;)

2023-08-02 21:50 UTC, vLesio commented on .coin/initialize-hooks.py
> +# This script initializes all the hooks present in the .coin\hooks folder
Yeah I bet you are <3 From what I can see you want me to provide reason **why** certain files are copied from one folder to another. The **WHY** will be included in the documentation when the system is ready to be deployed. This documentation will give context to what actions scripts need to perform, and scripts itself provide answer to **what** they do - this way we have no redundant information and the purpose is still known.

2023-08-03 06:40 UTC, vLesio commented on .coin/InitializeCoinAdditions.cs
> +        if (DateTime.Parse(text).AddHours(12) < DateTime.Now) {
To prepare the system that can manipulate this variable in a way acceptable for administrators would render this script too big - and that is why I'm trying to avoid it.

2023-08-06 10:44 UTC, empieniazek approved these changes

2023-08-06 10:44 UTC, empieniazek commented on .coin/coinadds.py
> +# This script runs all scripts that start with "initialize-" in the .coin folder
Is it still true?

2023-08-06 11:19 UTC, empieniazek approved these changes

2023-08-06 11:21 UTC, merged