Colliders fixed
AGH-Code-Industry/czasoport pull request #174
Opened 2024-05-05 09:32 UTC by Mikosztyla

Fixed:
- bug: crossing - hitboxy
- bug: crossing - czas przeszły

2024-05-07 18:33 UTC, Isdre requested changes
![image](https://github.com/AGH-Code-Industry/czasoport/assets/99088272/a2c46371-4255-42e1-b5c9-a35fec1e365c)
Wbiłem w przyszłości tam

2024-05-07 18:33 UTC, Isdre requested changes
![image](https://github.com/AGH-Code-Industry/czasoport/assets/99088272/a2c46371-4255-42e1-b5c9-a35fec1e365c)
Wbiłem w przyszłości tam

Nie da się bić do przeszłości *uznanie*

2024-05-18 15:12 UTC, Isdre requested changes
Ez
![image](https://github.com/AGH-Code-Industry/czasoport/assets/99088272/96ddf35f-1751-4ed3-9773-95aa2cf0bf40)

2024-05-18 20:21 UTC, KacperSobolak approved these changes
super będzie jak naprawisz to co Gilbert i będzie accept

2024-08-01 15:59 UTC, Isdre requested changes
![image](https://github.com/user-attachments/assets/7697a071-beb0-4e51-85fb-c7b0cb79ef2d)

1. Stanąć czerwonym punkcie.
2. Iść do góry.
3. Zmieniać czas w tą i z powrotem.
4. W odpowiedni momencie, pójdź w lewo, aby wypaść z mapy.

2024-08-31 15:06 UTC, Mikosztyla commented
Teraz powinno śwmigać

2024-09-12 15:17 UTC, merged