Bugfix/townhall new tilemap
AGH-Code-Industry/czasoport pull request #183
Opened 2024-05-14 13:31 UTC by BChochol

Changes on townhall scene regarding new way of building scenes and tilemaps to fix layer sorting problem

2024-05-14 20:33 UTC, KacperSobolak reviewed
tak to u mnie wygląda :( 
![image](https://github.com/AGH-Code-Industry/czasoport/assets/25562461/cd8a3da2-dfb8-4604-9919-1a59c80dd8e6)

2024-05-15 06:06 UTC, BChochol commented
a zobacz teraz, wrzucilem pare plikow .meta wydaje mi sie ze to naprawi a jak nie to bede dalej kombinowac

2024-05-15 15:23 UTC, Isdre requested changes
![image](https://github.com/AGH-Code-Industry/czasoport/assets/99088272/239e7a6c-02e0-4701-aa79-73450f748811)
Losowy młotek na crossing i w townhallu obok sali z kryształem, podłoga townhallu nadal nie działa.
**Ściany już git**, ale coś się stało ze strażnikiem i kryształ zniknął
![image](https://github.com/AGH-Code-Industry/czasoport/assets/99088272/d9490bd4-7b7b-4289-8345-cdb59c1a052b)
Strażnik przed urzędnikiem skacze
Urzędnik zniknął
![image](https://github.com/AGH-Code-Industry/czasoport/assets/99088272/f48d735a-608c-49b1-b536-cd655e4e331e)

2024-05-15 18:11 UTC, Isdre approved these changes

2024-05-18 13:07 UTC, Mikosztyla approved these changes
Git

2024-05-18 13:07 UTC, merged