Feature/save load dev
AGH-Code-Industry/czasoport pull request #200
Opened 2024-08-01 11:48 UTC by Isdre

ZANIM ZACZNIESZ ROBIĆ REVIEW PRZECZYTAJ TO:
- pamiętaj, aby dodać id do przedmiotów, na których chcesz robić testy
- powinno działać zapisanie pozycji gracza,itemów na mapie oraz zawartość ekwipunku

2024-08-18 09:25 UTC, Mikosztyla commented
1 ----------
Przed zapisem:
![image](https://github.com/user-attachments/assets/8be6da20-3b12-47c3-9d9a-78ecb004682e)
po ponownym włączeniu gry:
![image](https://github.com/user-attachments/assets/bf3490e6-ffb8-4de6-bd36-a8703b4cb3a0)
Zmienia się slot.
Czy to jest błąd? Jak dla mnie może zostać, raczej bez znaczenia.

2 ----------
Jeśli zapiszemy grę podczas tutorialu, to po ponownym włączeniu tutorial leci z wiadomościami od początku (nie ma w systemie do tutorialu gotowej funkcji, która pozwala go puścić z dowolnego momentu, więc raczej na razie musi zostać).

Tak to jak dla mnie działa super.

2024-08-18 18:44 UTC, Mikosztyla requested changes
Dla mnie bomba,

tylko pytanie czy dałoby się usunąć zmiany ze scen? One są niezbędne?

2024-08-18 21:14 UTC, Isdre reviewed
done

2024-08-21 16:13 UTC, KacperSobolak approved these changes
Komentarze do przemyślenia, ogólnie jest bardzo dobrze, działa fajnie, te rzeczy można w przyszłości zmienić, teraz może tak zostać

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/Scripts/DataPersistence/IPersistentObject.cs
> +        public SerializableGuid ID { get; set; }
czy to na pewno dobry pomysł, żeby w interface robić property?

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/Scripts/InteractableObjectSystem/PersistentInteractableObject.cs
> +        [field: SerializeField] public SerializableGuid ID { get; set; }
mega ciekawy atrybut, wcześniej go nie widziałem, fajnie że taki znalazłeś

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/Scripts/LevelTimeChange/TimeChange/TimeChanger.cs
> +        public bool SceneObject { get; } = false;
bool jest domyślnie ustawiony na false

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/Scripts/LevelTimeChange/TimeChange/TimeChanger.cs
> +        bool _hasCzasoport = false;
tak jak wyżej

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/Scripts/Utils/SerializableGuid.cs
> +                throw new ArgumentException("Must be SerializableGuid");
czy nie lepiej dać tylko loga, i zwrócić, że nie są takie same?

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/save.game
> +{"playerGameData":{"position":{"x":0.0,"y":2.7964653968811037},"inventory":[{"itemSO":{"instanceID":35152},"durability":9,"id":{"value":"12341234-1234-1234-1234-123412341234"}},{"itemSO":{"instanceID
w przyszłości, można pomyśleć nad szyfrowaniem tego, ale teraz nawet do testów może się przydać

2024-08-21 16:13 UTC, KacperSobolak commented on Assets/Scenes/Levels/Level0Market.unity
jeśli się da to można by było usunąć zmiany na scenach, jeśli nie to też nic się nie dzieje

2024-08-21 17:31 UTC, Isdre commented on Assets/Scripts/LevelTimeChange/TimeChange/TimeChanger.cs
> +        public bool SceneObject { get; } = false;
Wiem, ale to jest chyba bardziej czytelne.

2024-08-21 17:45 UTC, Isdre commented on Assets/Scripts/DataPersistence/DataTypes/DoorData.cs
> +        }
Jeszcze nie zajmowałem się na razie drzwiami. Miałem pomysł, żeby uprościć maksymalnie i zrobić klasę InteractableData z 1 zmienną int, która by odpowiadała za nr stanu obiektu. Wydaje mi się, że wtedy nie trzeba by było dodawać już nowy typów danych do zapisu.

2024-08-21 17:50 UTC, Isdre reviewed
Próbował coś zrobić z tymi zmianami na scenę, ale po zrzucaniu commitów i mergewaniu nic się nie zmieniło, więc chyba dałbym temu spokój.

2024-08-21 18:18 UTC, KacperSobolak commented on Assets/Scripts/LevelTimeChange/TimeChange/TimeChanger.cs
> +        public bool SceneObject { get; } = false;
To już kwestia dogadania się, zostawmy tak jak jest

2024-08-21 18:20 UTC, KacperSobolak commented
Wszystko już jasna, po mojej stronie jest approve, można mergować

2024-08-23 11:04 UTC, Mikosztyla approved these changes
Kox, tylko te sceny żeby ogarnąć

2024-08-23 11:12 UTC, merged